services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: postgresdb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
